pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }

  stages {
    stage('Checkout') {
      steps {
        // Pull code from GitHub
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Run Tests') {
      steps {
        sh 'npm test'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }
  }
}
