/* pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Run Tests') {
      steps {
        sh 'npm test'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }
  }
}  */
/*pipeline {
  agent none
  stages {
    stage('Checkout') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        sh 'npm install'
      }
    }

    stage('Run Tests') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        sh 'npm test'
      }
    }

    stage('Build') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        sh 'npm run build'
      }
    }
  }
} */
pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('node-pipeline') {
          sh 'npm install'
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir('node-pipeline') {
          sh 'npm test'
        }
      }
    }

    stage('Build') {
      steps {
        dir('node-pipeline') {
          sh 'npm run build'
        }
      }
    }
  }
}
